### ISSUE TITLE
crash when launching to sector pressure

### ISSUE THREAD

**Issue by ChristopherAMR** [3Snake3/ADC#23] opened 2023-10-29 21:35 UTC
"ArrayIndexOutOfBounds:
Index 16 out of bounds for lenght 16"

**Comment by 3Snake3** [comment] 2023-10-30 00:41
> "ArrayIndexOutOfBounds:
> Index 16 out of bounds for lenght 16"

Did you use another mods?
Because I tried to reproduce the issue now and everything works fine

**Comment by ChristopherAMR** [comment] 2023-10-30 09:04
> > "ArrayIndexOutOfBounds:
> > Index 16 out of bounds for lenght 16"
> 
> Did you use another mods? Because I tried to reproduce the issue now and everything works fine

I tried disabling all other mods but it still crashed

**Comment by 3Snake3** [comment] 2023-10-30 10:23
> > > "ArrayIndexOutOfBounds:
> > > Index 16 out of bounds for lenght 16"
> > 
> > Did you use another mods? Because I tried to reproduce the issue now and everything works fine
> 
> I tried disabling all other mods but it still crashed

Could you send me your save?

**Comment by ChristopherAMR** [comment] 2023-10-30 11:23
> > > > "ArrayIndexOutOfBounds:
> > > > Index 16 out of bounds for lenght 16"
> > > 
> > > 
> > > Did you use another mods? Because I tried to reproduce the issue now and everything works fine
> > 
> > 
> > I tried disabling all other mods but it still crashed
> 
> Could you send me your save?

here is the crash save that i recreated just now
[crash-report-10_30_2023_12_22_05.txt](https://github.com/3Snake3/Sapphirium/files/13204525/crash-report-10_30_2023_12_22_05.txt)

**Comment by 3Snake3** [comment] 2023-10-31 02:02
> > > > > "ArrayIndexOutOfBounds:
> > > > > Index 16 out of bounds for lenght 16"
> > > > 
> > > > 
> > > > Did you use another mods? Because I tried to reproduce the issue now and everything works fine
> > > 
> > > 
> > > I tried disabling all other mods but it still crashed
> > 
> > Could you send me your save?
> 
> here is the crash save that i recreated just now
> [crash-report-10_30_2023_12_22_05.txt](https://github.com/3Snake3/Sapphirium/files/13204525/crash-report-10_30_2023_12_22_05.txt)
> 

I meant game save

**Comment by Domaman202** [comment] 2023-11-03 07:37
I have a similar situation, keep a save file.
https://drive.google.com/file/d/1G1jeni9iB8KH_GDf8Cc7IXdmWuIyxNfG/view?usp=sharing

**Comment by Domaman202** [comment] 2023-11-03 07:38
and log
[crash-report-11_03_2023_14_35_15.txt](https://github.com/3Snake3/Sapphirium/files/13247649/crash-report-11_03_2023_14_35_15.txt)

**Comment by 3Snake3** [comment] 2023-11-03 08:45
> I have a similar situation, keep a save file.
> https://drive.google.com/file/d/1G1jeni9iB8KH_GDf8Cc7IXdmWuIyxNfG/view?usp=sharing

Idk.... I successfully landed on the Pressure with this save file... there's no crashes

**Comment by 3Snake3** [comment] 2023-11-03 08:46
Can you tell me when crash happens?

**Comment by 3Snake3** [comment] 2023-11-03 08:54
On the last build it crashes, on the BE it is not

**Comment by 3Snake3** [comment] 2023-11-03 10:19
Fixed. Reinstall the mod

**Comment by 3Snake3** [comment] 2023-11-03 10:20
@Domaman202 
@ChristopherAMR

**Closed as completed** 2023-11-03 10:19 UTC

**Comment by Domaman202** [comment] 2023-11-04 08:43
Thx bro <3
